#!/bin/bash

# create-migration-branch
# by: David Huie

# A script that creates a branch containing just the
# Rails migrations in the currently checked out branch.
# Use this utility to deploy your migrations prior to your
# feature.

commit_sha () {
    git rev-parse HEAD | sed 's/\(.\{7\}\).*/\1/'
}

git diff --exit-code 1>/dev/null 2>&1
if [ $? -ne 0 ]; then
    echo 'You have uncommited changes. Please commit your changes and then run this script again.'
    exit 1
fi

git fetch origin 2>/dev/null

DESTINATION_BRANCH="migrations-$(commit_sha)"
BRANCH_SHA="$(commit_sha)"
BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"
COMMON_SHA="$(git merge-base origin/master HEAD)"

git checkout -b $DESTINATION_BRANCH $COMMON_SHA
git checkout $BRANCH_SHA -- db/migrate db/schema.rb
git commit -m "Migrations for commit $BRANCH_SHA"
git checkout $BRANCH_NAME

echo
echo "Created migration branch: $DESTINATION_BRANCH"
