#!/bin/bash

# delete-merged-remote-branches
# by: David Huie

# This script determines which remote branches
# have been merged into origin's master and deletes
# them.

git fetch origin

git branch -r | grep origin | sed 's/origin\///' | grep -v master | grep -v deploy | xargs -I {} bash -c 'if [[ ! `git cherry origin/master origin/{}` ]]; then echo "deleting branch {}" && git push origin :{}; fi'
